name = "MovingConvection"

[deps]
ARMLive = "3cf54da3-541f-4d42-bdd0-41bf6096b485"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
ERA5Reanalysis = "99c076f5-c00e-46eb-a0bd-7ba31777c146"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DrWatson = "2.19.1"
julia = "1.12.4"
